# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-23 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('seoulcrawl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_client',
            name='join_date',
            field=models.DateField(default=django.utils.datetime_safe.date.today),
        ),
        migrations.AlterField(
            model_name='info_client',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
